hazelcast/hazelcast-reference-manual

- src/DistributedComputing.md
Incorrect markdown at code sample removed.
> Incorrect markdown removed

- src/Hibernate.md
> Added optional hibernate config to avoid NullPointerException with

- src/ClusterQuorum.md
- src/JCache-ICacheConf.md
little fix for quorum configuration along with cache-quorum
> cache quorum configuration

- src/HazelcastClusters/HazelcastClusters.md
- src/HazelcastClusters/JClouds.md
These changes already applied to EA branch after EA release more comprehensive documentation will be provided for jclouds.
> Adds jclouds section under clusters section.

- src/CPlusClient.md
Update for the 3.6 EA release.
> Update for the 3.6EA release.

- documentation.index
- src/HazelcastConfiguration/NetworkConfiguration.md
- src/UserDefinedServices.md
- src/spi/ExtendingHazelcast.md
- src/spi/config-properties/Config-Properties.md
- src/spi/discovery/DiscoveryIntegration.md
- src/spi/discovery/DiscoveryOverview.md
- src/spi/discovery/DiscoveryProvider.md
- src/spi/discovery/DiscoverySPI.md
- Combined all SPI related topics under a section called "Extending Hazelcast"
- Moved that new section right beneath "Hazelcast Configuration"
- Added Discovery SPI documentation and implementation example
- Added a small part to "Join" config
> Added Discovery SPI documentation draft

- src/Storage/HotRestartStore.md
This PR adds details about the design of persistence and garbage collection in the Hot Restart store.
> Add two sentences about Hot Restart

- src/SpringIntegration.md
This was not documented before. It was asked in a code-samples repository issue.
> spring cache abstraction additional configuration

- src/WAN/EventFiltering.md
Should be merged after : https://github.com/hazelcast/hazelcast-enterprise/pull/469
> Documentation update wan event filters after

- src/ManagementCenter.md
> Added javadoc descriptions for members

- src/Storage/HotRestartStore.md
See https://github.com/hazelcast/hazelcast/pull/7003
> Renamed hot restart home-dir to base-dir

- src/JMXAPIPerNode.md
Changes caused by: https://github.com/hazelcast/hazelcast/pull/7157
> JMX Total stats are removed

- src/HazelcastConfiguration/SystemProperties.md
- src/MonitoringWithJMX.md
Result of https://github.com/hazelcast/hazelcast/pull/7188
> JMX Total stats are optional now

- src/HazelcastJCache/JCache-ICacheConf.md
- src/Map-Eviction.md
Fixes https://github.com/hazelcast/hazelcast-reference-manual/issues/115
See https://github.com/hazelcast/hazelcast/pull/7272
> Improve & correct max-size-policy docs

- .gitignore
- build.sh
* Added temporary files to `.gitignore` so they are never committed by accident.
* Added LANG=en_EN to date command to override local language settings in `build.sh`.
* Fixed typos in `build.sh`.
For example on a build machine with a German locale the generated date would be `Publication Date : Mär 10, 2016` which looks quite awkward in an English manual.
> Small improvements

- src/PartitionGroupConfig.md
should be to "hazelcast.partition.count" not "hazelcast.map.partition.count"
> fixed "hazelcast.map.partition.count" doc error

- src/DDS.md
Fixes https://github.com/hazelcast/hazelcast/issues/7770
> Fixed Ringbuffer typo.

- src/ContinuousQuery.md
- src/Map-Interceptors.md
- src/Map-UsingHD.md
> Docs review

- src/ConfiguringHazelcast.md
- src/JavaClientConfiguration.md
- src/Logging.md
- src/Security.md
- src/SpringIntegration.md
- src/SystemProperties.md
Fixed schema URLs by removing http to https and www redirection.
> Fixed schema URLs

- src/AckTypes.md
- src/BatchMaximumDelay.md
- src/BatchSize.md
- src/DefiningWANReplication.md
- src/ResponseTimeout.md
- src/WAN.md
> WAN docs update

- src/CPlusClient.md
Updated the sections to include the newly added raw pointer based container adaptors and the query via Predicates feature.
> Updated C++ client section for RawPointer adaptors and the Query features.

- src/CPlusClient.md
- src/JavaClient.md
Updated the client feature comparison matrix and C++ client the raw pointer section.
> Feature comparison matrix needs to be updated

- src/Serialization.md
Enum is not among default serializers.
> Removes Enum from default serializers list

- src/WanSync.md
This new file should be added under "WAN/Wan Replication" section after "Acknowledge Types" title.
> Wan sync documentation

- src/SpringIntegration.md
Comes with https://github.com/hazelcast/hazelcast/pull/7469
> Documentation for Spring transaction manager

- src/SPICreateBackups.md
- src/SPICreateContainer.md
- src/SPIPartitionMigration.md
- src/SPIProxy.md
Adaption of https://github.com/hazelcast/hazelcast/pull/8673 for the reference manual.
> Replaced deprecated AbstractOperation with Operation

- src/RingBuffer.md
Code sample : https://github.com/hazelcast/hazelcast-code-samples/pull/131/files
> Adding manual chapter for ring buffer store

- src/UpgradingFrom3x.md
Describes incompatibility issues https://github.com/hazelcast/hazelcast/issues/9004 and https://github.com/hazelcast/hazelcast/issues/9006 and upgrade process.
> Added section on upgrading from 3.6.x to 3.7.3

- src/HotRestartPersistence.md
https://hazelcast.atlassian.net/wiki/display/EN/Hot+Restart+Usability+Improvements+on+Cluster+Restart+Design
> Doc update for Hot Restart when cluster.shutdown() is used

- src/HotRestartPersistence.md
- src/SystemProperties-Member.md
- src/SystemProperties.md
https://hazelcast.atlassian.net/wiki/display/EN/Copy+HRS+Data+from+a+Source+to+a+Target+Cluster+Design
> Doc update for Hot Restart IP address restriction removal

- src/HotRestartPersistence.md
https://hazelcast.atlassian.net/wiki/pages/viewpage.action?pageId=99123274
> Doc update for Hot Restart partial start

- src/ClusterSHScript.md
- src/RollingUpgrade.md
Adds documentation for rolling upgrades across minor versions.
@tombujok, @neilstevenson reviews & improvements are more than welcome.
> Rolling upgrades documentation

- src/HotRestartPersistence.md
Describe configuration options, mechanism, getting status and interruption for hot backup feature - https://hazelcast.atlassian.net/wiki/display/PM/Allow+Copying+of+HRS+from+Source+to+Target+for+Running+Source
> Hot backup documentation

- src/HotRestartPersistence.md
Added information on how to obtain HotRestartService since it was unclear on how to get the HotRestartService via public API.
> Added information on how to obtain HotRestartService

- src/NearCache.md
Depends on https://github.com/hazelcast/hazelcast/pull/9541
> Added note for multiple clients with enabled Near Cache preloader.

- src/RollingMemberUpgrades.md
To be merged after https://github.com/hazelcast/hazelcast/pull/9617 is merged to reflect minor change in log message
> Changed log message when cluster version is initially set or changed.

- src/NearCache.md
* Fixed `EvictionConfig` documentation
* Fixed wrong Near Cache names
* Adapted preloader documentation from `filename` to `directory`
I asked for an additional review from @tkountis, since he did the `filename` to `directory` fix.
Part of https://github.com/hazelcast/hazelcast-reference-manual/issues/232
> Fixed Near Cache documentation

- documentation.index
- src/EntryProcessorOptimizations.md
> Offloadable and ReadOnly manual entry

- src/JCache-ICache.md
> [BACKPORT] Additional information on starting a CacheManager

- src/JCache-ICache.md
Added examples & expanded reference sections on how a `HazelcastInstance` can be created or located when starting a `CacheManager`
The new content applies also for 3.8.1, will send a backport.
> Additional information on starting a CacheManager

- src/ManagementCenter.md
We will need to merge this into 3.8.1 branch when finished.
> [DO NOT MERGE] Add TLS/SSL only Management Center section

- src/ManagementCenter.md
This needs to be ported into 3.8.1 branch as well.
> Changes in Management Center LDAP configuration

- src/ManagementCenter.md
We should **NOT** merge this before https://github.com/hazelcast/management-center/pull/409 gets merged in.
> JAAS doc update

- src/LiteMember.md
See https://hazelcast.atlassian.net/wiki/display/PM/Gigantic+Cache+Migration+Enhancements requirement 6.
> Add lite member to data member promotion section

- src/ClusterSHScript.md
- src/ManagementCenter.md
- src/ManagingClusterState.md
See https://hazelcast.atlassian.net/wiki/display/PM/Gigantic+Cache+Migration+Enhancements requirement 3.
> Add info about NO_MIGRATION cluster state

- src/SystemProperties-Member.md
See https://hazelcast.atlassian.net/wiki/display/EN/Gigantic+Cache+Migration+Enhancements+Design
requirement 5.
> Added fragmented migration system property.

- src/NativeClientSecurity.md
Adds description of `<cache-permission>` element added in 3.8.2
> Adds cache-permission description

- src/ManagementCenter.md
This PR will also go to `master` branch.
> Metrics-only role for Management Center

- src/SystemProperties-Client.md
Added the new client system properties to enable and configure the client statistics.
> Added the new client statistics feature related system properties

- src/DataPartitioning.md
Lets wait for @mdogan's review before merging this one
> Major revision in Data Partitioning doc

- src/Map-Persistence.md
Added a note on the difference between  map.remove and map.delete and remove previous explanation
> updated for map.remove and map.delete

- src/NearCache.md
Port of https://github.com/hazelcast/hazelcast-reference-manual/pull/280
> Added new serialize-keys option to Near Cache chapter

- src/SystemProperties-Member.md
See https://hazelcast.atlassian.net/wiki/display/EN/Cluster+Service+Consistency+Improvements+Design
> Add system property for legacy member list format

- src/HotRestartPersistence.md
(cherry picked from commit a5f322c5fa423ec4c41c697bf292cc6ef84e47cf)
> Rename "Rolling upgrade" to "Rolling restart" under Hot Restart

- src/Diagnostics.md
Added section in diagnostics for 2 new plugins.
For more info see
https://hazelcast.atlassian.net/wiki/spaces/PM/pages/132385585/Heartbeat+diagnostics+plugin
> memberheartbeats and operationheartbeats diagnostics

- src/UpgradingFrom3x.md
Updated the JCache 3.6.x and 3.8.x incompatibility.
> Updat for the JCache 3.6.x and 3.8.x incompatibility problem

- src/SpringIntegration.md
- Clarify that hazelcast-spring jar is needed
- Give examples of exceptions for troubleshooting
> Fix Spring Integration dependencies

- src/OtherNetworkConfigurations.md
See: https://github.com/hazelcast/hazelcast/pull/11548
> Add section on member address provider SPI

- src/DefiningWANReplication.md
- src/EventJournal.md
Addressing review comments on: https://github.com/hazelcast/hazelcast-reference-manual/pull/284
> Minor updates to the WAN and event journal documentation

- src/Transactions.md
Note callout to warn on split-brain.
> Split-brain warning.

- src/ClusterEvents.md
This PR is just fixing code indentation in ClusterMembershipListener.
> Fix source code indentation in ClusterMembershipListener example

- src/WhyHazelcast.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/354
> Fix for #354

- src/DistributedQuery.md
- src/QueryCriteriaAPI.md
Improved indentation and aligned ctor argument names with field names.
Also the sample object type name was aligned in "Querying with Criteria API" section.
> Improve source code indentation in distributed query - Employee class sample

- src/EntryProcessorOptimizations.md
This PR makes the `OffloadableReadOnlyEntryProcessor` sample a standalone public class and improves the code indentation.
> Improve OffloadableReadOnlyEntryProcessor sample

- daux/docs/1100_Distributed_Query/500_Aggregators/300_Aggregations_Examples.md
- daux/docs/1300_Hazelcast_JCache/600_Hazelcast_JCache_Extension-ICache/700_JCache_Eviction.md
- daux/docs/400_Hazelcast_Overview/300_Why_Hazelcast.md
- daux/docs/800_Distributed_Data_Structures/100_Map/300_Map_Eviction.md
- src/AggregatorsExample.md
- src/JCache-Eviction.md
- src/Map-Eviction.md
- src/WhyHazelcast.md
See https://github.com/hazelcast/hazelcast-reference-manual/issues/386
> Fixed spelling of out-of-the-box

- daux/docs/700_Rolling_Member_Upgrades.md
- src/RollingMemberUpgrades.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/357
> Fix for #357

- daux/docs/1900_Management/400_Cluster_Utilities/600_Defining_Member_Attributes.md
- daux/docs/600_Setting_Up_Clusters/1100_Other_Network_Configurations.md
- daux/docs/600_Setting_Up_Clusters/800_Member_User_Code_Deployment_-_BETA.md
- daux/docs/600_Setting_Up_Clusters/850_Client_User_Code_Deployment_-_BETA.md
- daux/docs/600_Setting_Up_Clusters/900_Partition_Group_Configuration.md
- src/ClientUserCodeDeployment.md
- src/OtherNetworkConfigurations.md
- src/PartitionGroupConfig.md
- src/UserCodeDeployment.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/364
> Fix for #364 plus related extra improvements.

- daux/docs/1200_Transactions/100_Creating_a_Transaction_Interface.md
- daux/docs/1200_Transactions/200_Providing_XA_Transactions.md
- src/Transactions.md
- src/XATransactions.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/405
> Fix for #405

- daux/docs/800_Distributed_Data_Structures/200_Queue/300_Queue_with_Persistence_Datastore.md
- daux/docs/800_Distributed_Data_Structures/200_Queue/50_Getting_a_Queue_and_Putting_Items.md
- daux/docs/800_Distributed_Data_Structures/300_MultiMap.md
- daux/docs/800_Distributed_Data_Structures/400_Set.md
- daux/docs/800_Distributed_Data_Structures/500_List.md
- src/List.md
- src/MultiMap.md
- src/Queue-Persistence.md
- src/Queue.md
- src/Set.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/400
> Fix for #400

- daux/docs/800_Distributed_Data_Structures/100_Map/100_Getting_Map_and_Putting_Entries.md
- daux/docs/800_Distributed_Data_Structures/100_Map/1100_Listening_to_Map_entries_with_Predicates.md
- daux/docs/800_Distributed_Data_Structures/100_Map/1200_Removing_Bulk_Map_Entries_with_Predicates.md
- daux/docs/800_Distributed_Data_Structures/100_Map/1300_Adding_Interceptors.md
- daux/docs/800_Distributed_Data_Structures/100_Map/200_Backing_Up_Maps.md
- daux/docs/800_Distributed_Data_Structures/100_Map/300_Map_Eviction.md
- daux/docs/800_Distributed_Data_Structures/100_Map/500_Using_High-Density_Memory_Store_with_Map.md
- daux/docs/800_Distributed_Data_Structures/100_Map/600_Loading_and_Storing_Persistent_Data.md
- daux/docs/800_Distributed_Data_Structures/100_Map/800_Locking_Maps.md
- daux/docs/800_Distributed_Data_Structures/100_Map/900_Accessing_Entry_Statistics.md
- src/DDS.md
- src/Map-Backups.md
- src/Map-EntryStatistics.md
- src/Map-Eviction.md
- src/Map-Interceptors.md
- src/Map-ListenerWithPredicates.md
- src/Map-Locks.md
- src/Map-Persistence.md
- src/Map-UsingHD.md
- src/Map.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/389
> Fix for #389

- daux/docs/900_Distributed_Events/200_Distributed_Object_Events/800_Listening_for_Item_Events.md
- daux/docs/900_Distributed_Events/300_Event_Listeners_for_Clients.md
- src/ClientEvents.md
- src/DistributedObjectEvents.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/377
> Fix for #377

- src/JCache-AdditionalMethods.md
- src/JCache-HZInstance.md
- src/JCache-SpecCompliance.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/425
> Fix for 425

- src/EventFiltering.md
- src/ResponseTimeout.md
- src/SolaceIntegration.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/434
> Fix for #434

- daux/docs/1400_Integrated_Clustering/300_Integrating_with_Spring/100_Configuring_Spring.md
- daux/docs/1400_Integrated_Clustering/300_Integrating_with_Spring/200_Enabling_SpringAware_Objects.md
- daux/docs/1400_Integrated_Clustering/300_Integrating_with_Spring/300_Adding_Caching_to_Spring.md
- src/SpringIntegration.md
This PR contains code-snippets fixes for chapter about integrations.
> Fixes and typos in chapter 15 - Integrated clustering

- src/SpringIntegration.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/440
> Fix for #440

- src/ManagementCenter.md
Management Center Reference Manual link is updated with 3.9 version.
> Update for Management Center Reference Manual link

- src/PartitionGroupConfig.md
related to https://github.com/hazelcast/hazelcast-aws/issues/50 and https://github.com/hazelcast/hazelcast/pull/11934
added some clarifications to only ZONE_AWARE section.
> ZONE_AWARE section clarification

- daux/docs/1500_Storage/300_Hot_Restart_Persistence/1000_Hot_Backup.md
- daux/docs/1500_Storage/300_Hot_Restart_Persistence/500_Configuring_Hot_Restart.md
- src/HotRestartPersistence.md
* added required name attribute in XML
* used `CacheSimpleConfig` type
> Fix Hot Restart configuration snippets

- src/SystemProperties-Member.md
Also add caution for setting a lower value
> Update default value for hazelcast.mc.max.visible.instance.count

- daux/docs/1500_Storage/300_Hot_Restart_Persistence/200_Restart_Process.md
- src/HotRestartPersistence.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/467
> Fixing wrong target link.

- src/HotRestartPersistence.md
Will be applied to the daux sources after it is approved.
> Fix for #465

- src/JCache-Setup.md
- src/JCache-SpecCompliance.md
- src/JCache.md
- Updated section on running the TCK
- Adds information about behavioral changes in JCache 1.1 vs 1.0
> Updates regarding JCache 1.1 support

- daux/docs/2000_Security/550_Integrating_OpenSSL.md
- src/IntegratingOpenSSL.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/472
> Fix for #472

- daux/docs/1400_Integrated_Clustering/300_Integrating_with_Spring/100_Configuring_Spring.md
Related OS pull request: hazelcast/hazelcast#12214
> Cover all types in Spring namespace section

- src/DistributedObjectEvents.md
https://github.com/hazelcast/hazelcast-reference-manual/issues/412
> Adding note related to event threads.

- src/DefiningWANReplication.md
Fixes: https://github.com/hazelcast/hazelcast-enterprise/issues/1834
> Add info on discovery.useEndpointPrivateAddress WAN property

- src/ManagingClusterState.md
Fixes https://github.com/hazelcast/hazelcast-enterprise/issues/1803
> Add more info about NO_MIGRATION state

- src/Health.md
Add the documentation regarding the `healthcheck.sh` script.
Related PRD: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/398655566/Healthcheck+Scripts
Related TDD: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/502333716/Healthcheck+Scripts+Technical+Design+Document
> Add Health Check script

- src/Map-Eviction.md
closes https://github.com/hazelcast/hazelcast-reference-manual/issues/507
> Fix per-node eviction notes

- src/SplitBrainProtection.md
(cherry picked from commit dcd0e2c)
> Updates quorum configuration section

- src/docs/asciidoc/dds.adoc
- src/docs/asciidoc/wan.adoc
- src/main/java/distributedevents/Listen.java
- EntryLoadedListener
- LOADED events are not replicated by default
- persist-wan-replicated-data
> Added documentation related to latest WAN related additions:

- src/docs/asciidoc/security.adoc
This PR contains commits changing `security.adoc`.
- clean/trail line endings;
- update TLS related sections in the documentation;
> Update section about TLS

- src/docs/asciidoc/distributed_query.adoc
https://github.com/hazelcast/hazelcast-reference-manual/issues/562
> Adding content for "this" special attribute.

- src/docs/asciidoc/getting_started.adoc
This PR adds the documentation of user code deployment when member starts. See the related feature's PR: https://github.com/hazelcast/hazelcast/pull/13941
> add user code deployment while starting member feature documentation

- src/docs/asciidoc/management.adoc
Backport of #615.
This PR adds a description for disable scripting feature introduced by hazelcast/hazelcast#14116.
> Add Toggle scripting under Management Center section

- src/docs/asciidoc/security.adoc
> Fix OpenSSL Maven dependency snippet

- src/docs/asciidoc/wan.adoc
Cherry-picked two commits for adding section about dynamically adding WAN configuration.
>  Added section for dynamically adding WAN configuration

- src/docs/asciidoc/storage.adoc
- src/main/java/storage/SampleHotRestartConfiguration.java
See https://github.com/hazelcast/hazelcast/pull/14084 & https://github.com/hazelcast/hazelcast/pull/14365
PRD: https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1194131936/Option+for+Removing+Hot+Restart+Data+Automatically+Design
> Add explanation about Hot Restart auto removal of stale data

- src/docs/asciidoc/storage.adoc
Depends on https://github.com/hazelcast/hazelcast-enterprise/pull/2662/
> Update Hot Restart base-dir section for shared usage

- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/revision_history.adoc
Changed client attributes with client labels.
> Change client attributes with client labels

- src/docs/asciidoc/security.adoc
Updated credentials related code snippets with the most recent versions of them.
> update credentials related code snippets

- src/docs/asciidoc/setting_up_clusters.adoc
added url for k8s zone aware support. cc: @leszko
> adds kubernetes zone aware support

- src/docs/asciidoc/cp_subsystem.adoc
* Update is about proxy behaviour
> Update CP Subsystem docs

- src/docs/asciidoc/management.adoc
see https://github.com/hazelcast/hazelcast-reference-manual/pull/647/files#r264284930
> Fix curl of health ready check

- src/docs/asciidoc/performance.adoc
- src/main/java/performance/OrderKey.java
closes https://github.com/hazelcast/hazelcast-reference-manual/issues/614
> Cleanup sample code

- src/docs/asciidoc/getting_started.adoc
Reflect in documentation changes introduced in hazelcast/hazelcast#14798
> Cover package openings for OpenJ9 JVM

- src/docs/asciidoc/management.adoc
- src/main/java/extendinghazelcast/HostsDiscoveryStrategy.java
https://github.com/hazelcast/hazelcast/pull/14974
> Conform to unified attribute interface

- src/docs/asciidoc/getting_started.adoc
- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/management.adoc
Documented the behavior and limitations of updating the
license at runtime.
> Amended the documentation for the 'update license' REST API

- src/docs/asciidoc/understanding_configuration.adoc
Part of https://github.com/hazelcast/hazelcast/issues/14948
4.0 PR: https://github.com/hazelcast/hazelcast-reference-manual/pull/692
> [3.12.x] Refer to full example configurations in the manual

- src/docs/asciidoc/understanding_configuration.adoc
Part of https://github.com/hazelcast/hazelcast/issues/14948
3.12.x. PR: https://github.com/hazelcast/hazelcast-reference-manual/pull/693
> [4.0] Refer to full example configurations in the manual

- src/docs/asciidoc/distributed_query.adoc
- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/jcache/setup.adoc
- src/docs/asciidoc/management.adoc
- src/docs/asciidoc/serialization.adoc
- src/docs/asciidoc/setting_up_clusters.adoc
- src/main/java/ClientUCD.java
- src/main/java/MemberUCD.java
I recommend to review commit by commit.
@jerrinot Please check the part for member behavior
@sancar  Please check the client part
I did only superficially test what I wrote, the content is mostly based on discussions with other people.
> Improve User Code Deployment part

- src/docs/asciidoc/understanding_configuration.adoc
Related to https://github.com/hazelcast/hazelcast/pull/15224
> Adds clarification about dynamic configuration and user customizations

- src/docs/asciidoc/understanding_configuration.adoc
Related to https://github.com/hazelcast/hazelcast/pull/15225
Backport of #698
> [BACKPORT] Adds clarification about dynamic configuration and user customizations

- src/docs/asciidoc/dds.adoc
- src/main/java/dds/map/PersonEntryStore.java
EntryStore is explained as an extension to MapLoader with a few paragraphs. A full EntryStore implementation was added.
> Adds EntryStore

- src/docs/asciidoc/management.adoc
> [BACKPORT 3.12.z] Cover HTTPs related switches in cluster.sh and healthcheck.sh

- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/management.adoc
- src/docs/asciidoc/system_properties.adoc
This PR reflects changes made in https://github.com/hazelcast/hazelcast/pull/15036
> Add REST endpoint for instance name, system prop for Moby Names.

- src/docs/asciidoc/cp_subsystem.adoc
See https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1749090390/CP+Subsystem+Development+Mode+Design
> Information about CP unsafe mode.

- src/docs/asciidoc/distributed_events.adoc
- src/main/java/distributedevents/ClusterMigrationListener.java
Depends on https://github.com/hazelcast/hazelcast/pull/15071
See https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1749680489/Refactor+MigrationListener+API+Design
> Update MigrationListener section due to API change

- src/docs/asciidoc/cp_subsystem.adoc
- src/main/java/cp/CpSubsystemAPI.java
OSS PR: https://github.com/hazelcast/hazelcast/pull/15798
Please merge this after the OSS PR is merged.
> Rename CPSubsystemManagementService.restart() to .reset()

- src/docs/asciidoc/cp_subsystem.adoc
- src/main/java/cp/CpSubsystemConfiguration.java
Please merge this one after https://github.com/hazelcast/hazelcast/pull/15788 is merged
> Add documentation for initial permit count of Semaphore

- src/docs/asciidoc/getting_started.adoc
- src/docs/asciidoc/getting_started_HAZELCAST-MEMBER-TOOL.adoc
@Holmistr @Serdaro This should be merged while releasing 4.0.
> Rename StartServer => HazelcastMemberStarter

- src/docs/asciidoc/wan.adoc
- src/main/java/wan/ExampleWANReplicationConfiguration.java
- src/main/java/wan/ExampleWANReplicationDiscoveryConfiguration.java
Updates the WAN replication paragraph to conform to 4.0 state.
> Update WAN replication section for 4.0 changes

- src/docs/asciidoc/dds.adoc
- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/integrated_clustering.adoc
- src/docs/asciidoc/migration_guides.adoc
documentation of https://github.com/hazelcast/hazelcast/pull/15592
> New way of IMap eviction configuration

- src/docs/asciidoc/migration_guides.adoc
Added critical advice for upgrading from 3.x to 4.x
> Added advice for upgrading from 3.x to 4.x

- src/docs/asciidoc/dds.adoc
- src/docs/asciidoc/jcache/icache.adoc
- src/docs/asciidoc/migration_guides.adoc
- src/main/java/dds/map/MapCustomEvictionPolicyComparator.java
Required doc changes after merging https://github.com/hazelcast/hazelcast/pull/15939
> Changing IMap custom eviction policy configuration

- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/management.adoc
- src/docs/asciidoc/migration_guides.adoc
- src/docs/asciidoc/wan.adoc
Reflects changes because of https://github.com/hazelcast/hazelcast/pull/16087
> Updates to REST endpoints

- src/docs/asciidoc/management.adoc
- src/docs/asciidoc/migration_guides.adoc
- src/docs/asciidoc/preface.adoc
- src/docs/asciidoc/security.adoc
- src/docs/asciidoc/system_properties.adoc
- src/docs/asciidoc/understanding_configuration.adoc
- src/docs/asciidoc/wan.adoc
See [this core PR](https://github.com/hazelcast/hazelcast/pull/16161) for the list of changes.
Depends on: https://github.com/hazelcast/hazelcast/pull/16161
Depends on: https://github.com/hazelcast/hazelcast-enterprise/pull/3416
> Describe changes in Management Center configuration and REST API

- src/docs/asciidoc/hazelcast_clients.adoc
fixes https://github.com/hazelcast/hazelcast-reference-manual/issues/781
> Apply changes of connection retry config

- src/docs/asciidoc/management.adoc
- src/main/java/management/ExampleQueueStats.java
Depends on this OS PR: https://github.com/hazelcast/hazelcast/pull/16460
> Improve naming in LocalQueueStats

- src/docs/asciidoc/serialization.adoc
...since it is an internal detail in 4.0.
> Removed the mentions of the Data interface

- src/docs/asciidoc/understanding_configuration.adoc
Related to: https://github.com/hazelcast/hazelcast/pull/16411
> Remove InstanceListener references

- src/docs/asciidoc/management.adoc
Related to https://github.com/hazelcast/hazelcast/issues/16266
> Note on version compatibility of metric names

- src/docs/asciidoc/management.adoc
- src/docs/asciidoc/migration_guides.adoc
To be merged after https://github.com/hazelcast/hazelcast/pull/16539 has been approved and merged.
> Management center scripting is now disabled by default

- src/docs/asciidoc/management.adoc
Docs for hazelcast/hazelcast#16779
> Trusted interfaces for MC

- src/docs/asciidoc/management.adoc
Backport of #826 
Docs for hazelcast/hazelcast#16759
> [BACKPORT 4.0.z] Trusted interfaces for MC

- src/docs/asciidoc/system_properties.adoc
Fixes https://github.com/hazelcast/hazelcast-reference-manual/issues/836
> Docs for hazelcast.wait.seconds.before.join

- src/docs/asciidoc/security.adoc
This PR adds documentation for Kerberos configuration options (authentication & identity) introduced by hazelcast/hazelcast#17064.
> Additional Kerberos configuration parameters

- src/docs/asciidoc/security.adoc
This PR links a code-sample which is not merged yet: hazelcast/hazelcast-code-samples#453
> Auditlog added to Security chapter

- src/docs/asciidoc/cp_subsystem.adoc
- src/main/java/cp/event/CPGroupAvailabilityListenerImpl.java
- src/main/java/cp/event/CPMembershipListenerImpl.java
See related feature PR: https://github.com/hazelcast/hazelcast/pull/17037
> Add documentation for CP Subsystem listeners

- src/docs/asciidoc/distributed_sql.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/system_properties.adoc
This PR adds a new SQL section to the reference manual. It is placed before the predicate API section.
> Documentation for the SQL engine

- src/docs/asciidoc/extending_hazelcast.adoc
- src/docs/asciidoc/faq.adoc
- src/docs/asciidoc/hazelcast_clients.adoc
- src/docs/asciidoc/hazelcast_plugins.adoc
- src/docs/asciidoc/setting_up_clusters.adoc
- src/docs/asciidoc/wan/defining_wan_replication.adoc
- src/main/java/cp/CPSubsystemPersistence.java
Additionally, I updated Cloud plugin documentation parts.
> Auto detection documentation

- src/docs/asciidoc/distributed_sql.adoc
This PR adds more detailed documentation of the `SELECT` statement and supported expressions.
Closes https://github.com/hazelcast/hazelcast/issues/17593
> Improved SQL documentation (SELECT, expressions)

- src/docs/asciidoc/security.adoc
- src/docs/asciidoc/setting_up_clusters.adoc
Improvement related to hazelcast/hazelcast-enterprise#3779
CC @neilstevenson
> Emphasize the difference between Wildcards and Range characters

- src/docs/asciidoc/hazelcast_plugins.adoc
- src/docs/asciidoc/installing_upgrading.adoc
Updated all parts related to the Integration Modules. The content was very outdated.
> Update integration modules

- src/docs/asciidoc/jcache/icache.adoc
- src/docs/asciidoc/jcache/providers.adoc
- src/docs/asciidoc/migration_guides.adoc
Backport of #881 for 4.0.z branch
> [BACKPORT]  Updates JCache provider information

- src/docs/asciidoc/security.adoc
Documentation for changes introduced in hazelcast/hazelcast#17573 and hazelcast/hazelcast-enterprise#3786.
> Simplified Kerberos configuration added

- src/docs/asciidoc/system_properties.adoc
Related to hazelcast/hazelcast#17842
> Add system property hazelcast.ignoreXxeProtectionFailures

- src/docs/asciidoc/distributed_sql.adoc
Related discussion: https://hazelcast.slack.com/archives/C034YQBTG/p1606381165486400
> Enhancements to the SQL Unsupported features section

- src/main/java/clients/ListeningClients.java
Passing clientConfig to newHazelcastInstance
> Forgotten clientConfig pass

- src/docs/asciidoc/getting_started.adoc
Updated the C++ getting started section with the changes for 4.0 release.
> Correction to the C++ getting started section example code

- src/docs/asciidoc/getting_started.adoc
Current snippet uses ES5 syntax and seems to have some issues.
> Improve Node.js client snippet
