src/Hibernate.md

With the new design, hazelcast-all.jar must be present in the remote cluster's classpath when hibernate second level cache is used in native client mode. A note is added to documentation for this.

Docs update for new hibernate design

---

src/EntryProcessor.md
src/EntryProcessorAbstract.md

- Added missing description of backup EntryProcessor null issue, as discussed in https://github.com/hazelcast/hazelcast/issues/6162
- EntryProcessor.md: mostly copied the already existing information from the EntryBackupProcessor class javadoc
- EntryProcessorAbstract.md: added a note at the end. I wasn't sure how to correctly link to the Note section, so I attempted to link to the EntryProcessor Overview section. Please verify if the link works.

Added missing description of backup EntryProcessor null issue, as discussed in issue #6162

---

src/Hibernate.md

instance used by hibernate 2nd Level cache is smart client and Redo
Operation is true and cannot be changed by user configuration.

Adds additional info about hibernate native client mode. Client

---

src/Hibernate.md

Deprecated method is removed from documentation.
Alternative method added

HazelcastAccessor deprecated. Adds alternative method.

---

src/Management/MonitoringWithJMX.md

We should not use private API in the reference manual.
It would be nice if this could be fixed in the public release as soon as possible.

Fixed usage of private API in MonitoringWithJMX

---

src/ClusterSHScript.md
src/ManagementCenter.md
src/QuerySQL.md

I got errors like this when building the PDF locally:
```
! LaTeX Error: Command \textquotesingle unavailable in encoding T1.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...                                              
l.9329 ...t{name\ LIKE\ \textquotesingle{}Jo\%‘}
pandoc: Error producing PDF from TeX source
```
Fixed by using a different single quote character, as already done in other places.

Fixed single quotes in code which broke PDF generation

---

build.sh

Made the PDF creation skipable with the parameter "--skipPDF" (needs to be the second argument after the version number. This is useful for developers who want to maintain their documentation and need a fast way to update the final HTML output.
Example usage:
`build.sh 3.6 --skipPDF`

Skipable PDF creation

---

src/Map-ListenerWithPredicates.md
src/SystemProperties-Member.md

Updated documentation on usage of new property `hazelcast.map.entry.filtering.natural.event.types` introduced in version 3.7 that alters listener-with-predicate behavior

Updated map listener with predicate documentation

---

src/OtherNetworkConfigurations.md

we have renamed hazelcast-cloud as hazelcast-aws. 
this is small explanation for that change. @Serdaro, i am not sure, maybe we should put this explanation to another section.

added small aws explanation

---

src/JavaClientSystemProperties.md
src/SystemProperties-Member.md
src/SystemProperties.md

Added the two new system properties hazelcast.compatibility.3.6.client and hazelcast.compatibility.3.6.server.

Add hazelcast 3.6.x compatibility switch flag per PR #9066

---

src/ConfiguringHazelcast.md
src/HazelcastConfiguration.md
src/Map-Persistence.md
src/Map.md
src/NativeClientSecurity.md

Links to "Using wildcards" section were set;
http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#using-wildcard
which doesn't exist.
I've changed them to;
http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#using-wildcards

Fix broken links for using-wildcards section

---

src/ConfiguringHazelcast.md
src/HazelcastConfiguration.md
src/Map-Persistence.md
src/Map.md
src/NativeClientSecurity.md

Backport of: https://github.com/hazelcast/hazelcast-reference-manual/pull/199

Backport: Fix broken links for using-wildcards section

---

documentation.index
src/Lock.md
src/Map-Locks.md
src/Queue-Configuration.md
src/Queue-Quorum.md

Extend existing quorum support to lock and queue actions. Add configuration examples, description, implementation details, gotcha's and examples. PRD : https://hazelcast.atlassian.net/wiki/display/PM/Cluster+Quorum+for+Queue+and+Lock

Extend existing quorum support to lock and queue

---

src/Transactions.md

When a transaction spans multiple partitions, the user might observe
partially committed data - missing data, both old and new data, etc.
Related : https://github.com/hazelcast/hazelcast/issues/8531

Add caveat on transaction isolation

---

documentation.index
src/NetworkPartitioning.md
src/Split-BrainRecovery.md
src/SplitBrainProtection.md

Improved network partitioning, split-brain protection and split brain recovery sections.
Related to https://github.com/hazelcast/hazelcast-reference-manual/pull/300

Improve network partitioning

---

src/EntryProcessorSampleCode.md

Just fixed method name according to the code sample.

EntryProcessorSampleCode.md mistype fix

---

src/SystemProperties-Client.md
src/SystemProperties-Member.md

Reduced member heartbeat timeout to 1 minute from 5 minutes. Default 5min
Master confirmation timeout is reduced to 150s from 350s.
Additionally removed some client system properties which are written
in member system properties page.
See https://github.com/hazelcast/hazelcast/pull/11333

Reduce member heartbeat timeout to 1min from 5mins

---

src/Diagnostics.md

Added the mapstore diagnostics to the default set of plugins
Added a documentation section for the new filename prefix option.
fix https://github.com/hazelcast/hazelcast-reference-manual/issues/316

Minor diagnostics improvements

---

src/JCache-SplitBrain.md
src/SplitBrainRecovery.md

The default Cache merge policy in 3.9 is updated to "Put If Absent" merge policy by https://github.com/hazelcast/hazelcast/pull/11582.
@Serdaro we should ensure the change of default from Pass-Through to put-if-absent is documented in the release notes as well.

Updated default Cache merge policy in 3.9

---

src/DurableExecutorService.md
src/PartitionGroupConfig.md

Updated documentation of ZONE_AWARE to mention now supported ZONE_AWARE for AWS Discovery. Please also check if updates regarding DurableExecutorService are still valid as for some reason, they were hidden in my repo for a long time.

ZONE_AWARE update in reference manual

---

src/UnderstandingConfiguration.md

Removed wrongly included space char from 'hazelcast.config' system property configuration example.

Fixed typo in -Dhazelcast.config example

---

src/OtherNetworkConfigurations.md

* Fixed `setPublicAddress()` call example - the method takes just one String argument.
* Fixed port configuration example - 
* argument types: String->int
* removed semicolon
* `setPortCount()` doesn't support fluent API (see hazelcast/hazelcast#11669).

Fixed network configuration examples

---

src/ExecutionCallback.md
src/ExecutionCancellation.md

This PR fixes the `Fibonacci`sample implementations in chapter 10. Distributed Computing.
The original implementation wrongly used a Long  generic type argument for the class.
Also the empty no-args constructor is removed by this PR to make the implementation simpler/shorter..

Fix Fibonacci execution samples

---

src/DistributedObjectEvents.md

This PR improves MultiMap example - `SampleEntryListener`:
* removes wrapping `Listen` class (the listener registration code fragment is still present in the the text)
* adds missing methods from `EntryListener` interface
* fixes listener class name in the registration snippet

Fix MultiMap entry listener samples

---

src/ClusterEvents.md

This PR contains fixes for `SampleDistObjListener` example:
* `getId()` method is not part of the `DistributedObjectListener` interface
* `main(String[])` method removed as the sample usage follows in the text
* service name added to output
* the `distributedObjectDestroyed` event doesn't try to retrieve the distributed object from the instance anymore. It threw `DistributedObjectDestroyedException`.

Fix SampleDistObjListener example

---

src/DistributedObjectEvents.md

This PR
* updates output of `Listen` class
* moves a prevent-thread-starvation java snippet to a correct section
* fixes typo in `addPartitionLostListener` sample

Fix sample output of Listen class

---

src/DistributedObjectEvents.md

This PR fixes the `SampleItemListener` example:
* removes `main()` method (as the listener registration is covered subsequently in the text)
* corrects method argument types (to fit `ItemListener`)
* fixes typo (variable name) in listener registration registration snippet

Fix SampleItemListener example

---

src/UnderstandingConfiguration.md

https://github.com/hazelcast/hazelcast-reference-manual/issues/355
Note about the "- D" typo: It was fixed previously with https://github.com/hazelcast/hazelcast-reference-manual/pull/359

Fix for #355

---

src/SettingUpClusters.md

Use an anchor instead of full link to a devel version.

Fix link pointing to Discovery SPI section

---

src/EntryProcessorSampleCode.md

This PR fixes `EntryProcessorTest` sample code:
- fixed typos and wrong return types
- added generic types to avoid "Raw type" compiler warnings

Fix EntryProcessorTest Java code - typos, filling-in generic types

---

src/DurableExecutorService.md

This PR fixes code snippet and information about capacity.
Configuring 0 as a capacity value is not allowed:
```
Exception in thread "main" java.lang.IllegalArgumentException: Capacity should be greater than 0
at com.hazelcast.util.Preconditions.checkPositive(Preconditions.java:198)
at com.hazelcast.config.DurableExecutorConfig.setCapacity(DurableExecutorConfig.java:156)
```

Fix DurableExecutorConfig example - int method arguments, call order

---

src/ExecutionMemberSelector.md

This PR fixes the MyMemberSelector example:
* the `getAttribute(String)` method is not specified in the Member interface

Fix MyMemberSelector example snippet

---

src/ExecutionCallback.md

This PR contains fixes for task callback example:
* added name argument to the `getExecutorService()` method call
* added missing parentheses for `es.submit()` call
* removed imports (not all the required ones were used; and they are already mentioned in some snippets above)

Fix task callback snippet for Fibonacci example

---

src/DistributedObjectEvents.md

This PR simplifies the `SampleMessageListener` and fixes snippet related to its registering in a topic.

Fix SampleMessageListener code snippets

---

src/XATransactions.md

* added imports - as for instance the `Transaction` lives in both Hazelcast and JTA
* removed Atomikos dependencies - let user to choose the JTA implementation (Atomikos, Narayana, ...) - by using `UserTransactionManager` we wire the Atomikos specific API into the sample
* removed `delistResource()` usage - it's only confusing in the example. The delistResource call should be used only in specific cases (see e.g. https://stackoverflow.com/a/7173868/653069)

Improve XA transactions sample

---

src/ClusterEvents.md
src/DistributedObjectEvents.md

Issues fixed:
* removed `-` (minus) character from sample package name
* unified indentation in listener registration XML snippets
* `listener(s)` used instead of `partition-lost-listener(s)` in the `ConsoleLoggingPartitionLostListener` sample

Fix cluster listener registration snippets - indentation, package names, XML element names

---

daux/docs/1300_Hazelcast_JCache/600_Hazelcast_JCache_Extension-ICache/100_Scoping_to_Join_Clusters.md
src/JCache-ICache.md

The original `setProperty(...)` call can only be used for `String` arguments.

Fix setting HAZELCAST_INSTANCE_ITSELF as JCache CacheManager property

---

daux/docs/1300_Hazelcast_JCache/600_Hazelcast_JCache_Extension-ICache/500_ICache_Async_Methods.md
src/JCache-AsyncOperations.md

The `putAsync()` returns `Void` future, let's use `getAndPutAsync()` call instead.

Fix ICache async call example snippet

---

daux/docs/1300_Hazelcast_JCache/200_Setup_and_Configuration/300_Configuring_for_JCache.md
daux/docs/1300_Hazelcast_JCache/400_JCache_API/100_JCache_API_Application_Example.md
daux/docs/1300_Hazelcast_JCache/400_JCache_API/300_Implementing_Factory_and_FactoryBuilder.md
daux/docs/1300_Hazelcast_JCache/400_JCache_API/800_Implementing_ExpiryPolicy.md
daux/docs/1300_Hazelcast_JCache/600_Hazelcast_JCache_Extension-ICache/600_Defining_a_Custom_Expiry_Policy.md
documentation.index
redirect-latest-dev.js
redirect-latest.js
src/JCache-API.md
src/JCache-APIFactory.md
src/JCache-CustomExpiryPolicy.md
src/JCache-ExpiryPolicy.md
src/JCache-JCacheConfiguration.md

This PR contains 2 commits related to JCache section. 
* The first just fixes minor typo (missing dot) in an example code snippet.
* The second replaces occurrences of `ExpirePolicy` (wrong) with `ExpiryPolicy` (correct) across the manual.

Fix JCache ExpiryPolicy

---

daux/docs/1500_Storage/100_High-Density_Memory_Store.md
src/ConfiguringHD.md

Fix which uses the `NativeOutOfMemoryException` type instead of *Native `OutOfMemoryException`*.

Fix reference to NativeOutOfMemoryException type

---

src/RingBuffer.md

Previously the manual stated Ringbuffer as a distributed structure, contradicting its javadoc:
manual: "Hazelcast Ringbuffer is a distributed data structure..."
javadoc: "Ringbuffer currently is not a distributed data-structure..."
This change in pair with a javadoc change brings the two docs into sync.

Sync Ringbuffer manual and javadoc

---

src/JCache-Setup.md
src/JCache-SpecCompliance.md
src/JCache.md

- Updated section on running the TCK
- Adds information about behavioral changes in JCache 1.1 vs 1.0

Updates regarding JCache 1.1 support

---

daux/docs/2000_Security/900_Native_Client_Security.md
src/NativeClientSecurity.md

This commit 
* adds a sentence:
> The default permission policy allows to use comma separated names in the principal attribute configuration.
* changes the code snippet to show comma-separated principal names

Describe possibility of comma-separated principals in permissions configuration when the default permission policy is used.

---

src/ISemaphore-Quorum.md

`ISemaphore.increasePermits()` is a new operation [introduced with 3.10](https://github.com/hazelcast/hazelcast/pull/7859).
Master PR: #519

Add increasePermits to ISemaphore docs' quorum section

---

src/docs/asciidoc/setting_up_clusters.adoc

Fix for issue https://github.com/hazelcast/hazelcast-reference-manual/issues/536

Fixed Incorrect fragment part of url for 'multicast element' in Reference manual

---

src/docs/asciidoc/security.adoc

* Removed `SunX509` algorithm from the snippet (as it'll be used as a default).
* Added comment about keystore attributes on client-side
The keystore setting is only required on client side, when the mutual authentication is enabled.

OpenSSL snippet update

---

src/docs/asciidoc/jcache/icache.adoc

ICache section mentions overloaded methods that enable users to use custom expiry policies per call. I think we can also mention `setExpiryPolicy` method because it is also another way to use custom expiry policies that JCache does not provide.
This is a new feature introduced in 3.11

Mentions `setExpiryPolicy` in ICache

---

.gitignore
src/docs/asciidoc/management.adoc

This PR fixes failing build by adding a new-line in a log snippet (in 3rd commit).
There are 2 other commits which are just cosmetic:
* gitignore update
* removing trailing spaces in `management.adoc`

Fix management snippet

---

src/docs/asciidoc/security.adoc

This PR improves OpenSSL related content and describes changes introduced in hazelcast/hazelcast-enterprise#2398 (not yet merged!):
* OpenSSL native configuration way using PKCS#8 key files is preferred

Improve security section related to usage of native TLS libraries (OpenSSL, BoringSSL)

---

src/docs/asciidoc/getting_started.adoc

This PR contains 2 commits. The first just fixes formatting (trailing spaces) without content changes.
The second commit adds a section related to using Hazelcast in Java Module System (i.e. Java 9 and newer).

[Java-9] running Hazelcast in modular environment

---

src/docs/asciidoc/wan.adoc

- Evicted entries are not synchronized
- Increasing partition count is increasing the efficiency of the Merkle synchronization

Add notes for WAN synchronization

---

src/docs/asciidoc/wan.adoc

- Brief introduction of the Merkle sync process, defining the terms consistency check and synchronization
- Notes on memory consumption
- Notes on defining the tree depth
- REST API
- Statistics (diagnostics, MC)
The human-readable version of the changes can be seen here:
https://github.com/blazember/hazelcast-reference-manual/blob/3.11/wan-merkletree/details-guidance/src/docs/asciidoc/wan.adoc#the-process

Add details to the Merkle tree WAN section

---

src/docs/asciidoc/wan.adoc

Explaining and moving difference count column.
Thanks @gokhanoner for the suggestion.

Explain difference count in Merkle tree sync section

---

src/docs/asciidoc/network_partitioning.adoc

A few simple fixes to make it more readable.

Tidy up Network Partitioning text.

---

src/docs/asciidoc/system_properties.adoc

hazelcast.mancenter.home parameter has no effect for the members. It is
used by MC and documented on MC reference manual.

Remove obsolete MC param

---

src/docs/asciidoc/security.adoc

[BACKPORT 3.11.z] Fix OpenSSL Maven dependency snippet

---

src/docs/asciidoc/system_properties.adoc

hazelcast.mc.max.visible.instance.count parameter was removed in 3.11.

Remove obsolete MC parameter

---

src/docs/asciidoc/system_properties.adoc

hazelcast.mc.max.visible.instance.count parameter was removed in 3.11.

[BACKPORT] Remove obsolete MC param

---

src/docs/asciidoc/distributed_query.adoc
src/docs/asciidoc/getting_started.adoc
src/docs/asciidoc/security.adoc

Also removes a section on Java 6/7 vs 8 in Aggregations documentation
since this is no longer relevant.

Updates JVM compatibility table (min Java 8 requirement since 3.12)

---

src/docs/asciidoc/performance.adoc

Noticed a typo in the pipelining section while writing a documentation for that feature for the node.js client. `debt` should be `depth`

fix typo in the pipelining documentation

---

build.gradle
src/docs/asciidoc/jcache/overview.adoc
src/docs/asciidoc/jcache/setup.adoc
src/docs/asciidoc/jcache/tck.adoc

Backport of #688 
To be merged as soon as https://github.com/hazelcast/hazelcast/pull/15009 & https://github.com/hazelcast/hazelcast-enterprise/pull/2958 are merged.

Updates for JCache 1.1.1 support

---

src/docs/asciidoc/management.adoc

There are 2 commits, the first just fixes spaces within `management.adoc`. The new content is part of the second commit.

Cover HTTPs related switches in cluster.sh and healthcheck.sh

---

src/docs/asciidoc/hazelcast_clients.adoc

When curl params "-X POST" and -d "" are sent altogether curl warns "Note: Unnecessary use of -X or --request, POST is already inferred.". Only -d "" is necessary in our examples.
Also, when response body is empty we do not send "Content-type" but examples show that we do. This is also fixed.
Fixes hazelcast/hazelcast#15491

Omit unnecessary flags in curl and Content-type on empty responses

---

src/docs/asciidoc/getting_started.adoc
src/docs/asciidoc/hazelcast_clients.adoc
src/docs/asciidoc/management.adoc

Added the POST /hazelcast/rest/license endpoint to the
CLUSTER_WRITE group ("Using the REST Endpoint Groups").
Added an example in "License Information / REST".
Documented the behavior and limitations of updating the
license at runtime.
Note: OS/EE code already reviewed and merged.

Added documentation for the new 'update license' REST API (forward port from maintenance 3.x)

---

src/docs/asciidoc/storage.adoc

Added note that smaller values give better performance when persistent memory is
used.

Improved persistent memory manual

---

src/docs/asciidoc/management.adoc

Always returns 0, looks like there is no replacement.
OS counterpart: https://github.com/hazelcast/hazelcast/pull/15676

Remove deprecated LocalReplicatedMapStats.getReplicationEventCount

---

src/docs/asciidoc/getting_started.adoc

...as an extra Maven dependency in the 'Installing Hazelcast IMDG Enterprise' section.

Javadoc JAR for EE: added an example

---

src/docs/asciidoc/migration_guides.adoc

Addresses interfaces such as:
- EntryProcessor (https://github.com/hazelcast/hazelcast/pull/14995)
- Projection (https://github.com/hazelcast/hazelcast/pull/15204)
- ValueCallback and ValueExtractor (
https://github.com/hazelcast/hazelcast/pull/15216). Changes on
ArgumentParser, ValueCollector, ValueReader are either internal or have
no effect on user code.
Also, added some samples.

Improve section on lambda-friendly-interfaces

---

src/docs/asciidoc/migration_guides.adoc

Note - I might have gone overboard with putting both XML and Java samples in the same column in one table. You can adapt this as you see fit.
Leftover:

Update migration sections for WAN replication changes

---

src/docs/asciidoc/security.adoc

This PR reorders TLS sections and adds a new subsection related to updating key material in the running cluster.

Add a new section related to updating TLS certificates

---

src/docs/asciidoc/hazelcast_clients.adoc
src/docs/asciidoc/management.adoc
src/docs/asciidoc/migration_guides.adoc
src/docs/asciidoc/rolling_member_upgrades.adoc
src/docs/asciidoc/setting_up_clusters.adoc
src/docs/asciidoc/system_properties.adoc

- `hazelcast.rest.enabled`, `hazelcast.memcache.enabled` and
`hazelcast.http.healthcheck.enabled` were in fact removed with
https://github.com/hazelcast/hazelcast/pull/15981
- fixed WAN replication configuration
- "group property" has been renamed to "cluster property"

Minor updates for latest state of 4.0

---

src/main/java/wan/EnablingWRforCache.java
src/main/java/wan/EnablingWRforMap.java

* Counterpart of this core PR: https://github.com/hazelcast/hazelcast/pull/16403
* Fixes compilation of `WanReplicationRef` samples
cc @mmedenjak

Rename WanReplicationRef#setMergePolicy to setMergePolicyClassName in samples

---

src/docs/asciidoc/hazelcast_clients.adoc

This documentation update corresponds to the code update in hazelcast ticket 13938.

Explain that the trailing slash will be stripped from the map REST calls

---

src/docs/asciidoc/management.adoc

- Removed beans based on https://github.com/hazelcast/hazelcast/pull/16425
- Fixed name of `HazelcastInstance.PartitionServiceMBean` https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/jmx/PartitionServiceMBean.java

Update JMX docs for v4.0+

---

src/docs/asciidoc/security.adoc
src/test/java/security/CustomLoginModuleTest.java

As the Hazelcast Security is the Enterprise feature we don't need to repeat it in subsections, I think. Moreover not all the subsections had the note included.

Leave the EE feature note just once in the Security chapter

---

build.gradle

When developing refmanual, you could now use `./gradlew -PskipPdf build` to speed up the build. And before the release, we don't have to edit anything, so it's good for the automation.

Added skipPdf flag for development purposes

---

src/docs/asciidoc/hazelcast_clients.adoc

These are possibly leftovers from the config changes that involved
group name and password. Client config does not have such an
element anymore.

Remove references to cluster password

---

src/docs/asciidoc/understanding_configuration.adoc

JobTracker was part of the Map/Reduced framework which was removed in Hazelcast 4

JobTracker is no longer part of Hazelcast

---

src/docs/asciidoc/index.adoc
src/docs/asciidoc/revision_history.adoc

The motivation for this change is to get user's attention to the content ASAP. I doubt that the average user is actually reading the content very often. I believe that people look at release notes and see what changed in the version, not directly in the content of the document.
I still believe that it's a very valuable page, but not that much that it would deserve to be in the very first pages. It makes more sense to me in the PDF file, but not on the website where the user is trying to find the information about IMDG ASAP.
BTW I love how easy it was to propose the change :)

Move 'Document Revision History' to appendix

---

src/docs/asciidoc/installing_upgrading.adoc
src/docs/asciidoc/management.adoc
src/docs/asciidoc/management/license_info.adoc
src/docs/asciidoc/management/management_center.adoc
src/docs/asciidoc/security.adoc
src/docs/asciidoc/storage.adoc
src/docs/asciidoc/wan/index.adoc

At first sights, this PR introduces quite a few changes, but it's almost all reordering of the sections, putting them in better places to enhance and simplify the flow the (especially new) user.
Assumptions:
* Users want to setup Hazelcast ASAP. They want to pick the installation way that suits them and run it right away. For that, they need overview of these options and also get to the installation information ASAP. Miscellaneous stuff can wait.
* CLI will be the advertised way of installation as we continue with further improvements.
Changes made:
* Introduced CLI way of installation
* Reordered the installation ways from the easiest (CLI) to the most difficult, but most powerful (Download Archives)
* Encapsulated the various cloud deployment methods into a subsection to have a logical …

Rewamp 'Installing and Upgrading' chapter

---

src/docs/asciidoc/dds.adoc
src/docs/asciidoc/distributed_query.adoc

Updates IMap packages from `core` to `map`
Also in `src/docs/asciidoc/getting_started.adoc#72` there is one more `core.IMap` in the code snippet but since I was not able to find the corresponding content in the doc I kept it unchanged - may be it's not supposed to be upgraded to 4.x at all.

Fix IMap packages.

---

src/docs/asciidoc/jcache/icache.adoc
src/docs/asciidoc/jcache/providers.adoc
src/docs/asciidoc/migration_guides.adoc

Since https://github.com/hazelcast/hazelcast/pull/17320 was merged, new public class names should be advertised for JCache provider configuration. Also aligns to "member" terminology instead of "server" and removes some redundant info from the JCache providers section.
Fixes #854 on `master` branch.

Updates JCache provider information

---

src/docs/asciidoc/security.adoc

This PR adds a section explaining default authentication in the Security chapter.
Related to: https://github.com/hazelcast/hazelcast-jet-enterprise/issues/134#issuecomment-700503527
Also, a few other small improvements are included.

Improve security chapter - add Default Authentication section and do some clean-up

---

src/docs/asciidoc/installing_upgrading.adoc

Use 4.0 and 4.1 versions instead of 3.12 and (the non-existent) 3.13.
Also, added enterprise to the jar names as rolling upgrade is an
enterprise feature.

Update rolling upgrade versions

---

src/docs/asciidoc/distributed_query.adoc

There were some problems with that chapter. Namely,
- Explanation of the code sample was not clear. For example, ``values``
should refer to the method call, but it was used in plural form, probably
referring to the returned collection.
-  If the comparator is not set, keys or values of the collection should
be comparable, not the collection itself.
- The note about the transactional context is not related to the paragraphs
above. It makes sense to convert it into a note.
Credit goes to Andrey for spotting these problems on https://github.com/hazelcast/hazelcast-python-client/pull/232

Clarify the paging predicate chapter

---

src/docs/asciidoc/understanding_configuration.adoc

Client-specific entries need to start with `HZCLIENT` and not `HZ_CLIENT`

Fix a bug in 'configuration override section'

---

build.gradle
src/docs/asciidoc/installing_upgrading.adoc

Fixes #797 
- Reformatted the table to list only supported JDKs and their versions
- Added a note with a link to previous manuals for supported JDKs of older versions of Hazelcast
- Fixed the broken link to the TLS/SSL section

Update list of supported JVMs

---

src/docs/asciidoc/dds.adoc

Added extra clarity about what happens when `initial-mode` is set to `LAZY` in `MapStore` and `MapLoader` implementations.
Updated some phrasing to make information more concise/clear.
This PR addresses the issues that were raised in [support ticket 6747](https://hazelcast.zendesk.com/agent/tickets/6747)

Make the difference between LAZY and EAGER modes clearer
